### PR TITLE
upgrade to latest sbt 1.3.x version (1.3.13)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[error] /Users/tisue/scala-ssh/src/main/scala/com/decodified/scalassh/ScpTransferable.scala:52:33: not enough arguments for constructor LoggingTransferListener: (x$1: net.schmizz.sshj.common.LoggerFactory)net.schmizz.sshj.xfer.LoggingTransferListener.
[error] Unspecified value parameter x$1.
[error]   private def defaultListener = new LoggingTransferListener
[error]                                 ^
[error] /Users/tisue/scala-ssh/src/main/scala/com/decodified/scalassh/SshClient.scala:63:44: implicit numeric widening
[error]         case Some(timeout) => channel.join(timeout, TimeUnit.MILLISECONDS)
[error]                                            ^
```

I saw this same error in the Scala community build and thought I should report it, so this PR is a way of reporting it.

**Comment by sirthias** [comment]
Thank you, Seth!

**Comment by SethTisue** [comment]
I should probably have said: I don't know what's going on here. My best guess would be that the newer sbt is using newer Coursier and that something changed in the handling of transitive dependencies, leading to a different, unexpected set of library versions on the classpath.

**Comment by sirthias** [comment]
This is indeed a strange problem.
No idea, what's happening underneath.
The fix I applied now is easy, but I still don't quite understand, where the version conflict comes from.
Anyway, should be working now...

Thanks again for the PR, Seth!

**Comment by SethTisue** [comment]
https://github.com/scala/community-build/commit/25d9ddee9bad1d2e5c808be17e708bbb97eceb04 👍

**Pull request merged**
